const maps=[
["bind","バインド","assets/bind.png","テレポーターを活用する2サイト構成。",["Aサイト","Bサイト","Aショート","Bロング","フッカー","ランプ","シャワー","ガーデン"],["レイズ","ジェット","ネオン","ブリムストーン","ヴァイパー","オーメン","ゲッコー","ソーヴァ","フェイド","サイファー","キルジョイ","セージ"]],
["haven","ヘイヴン","assets/haven.png","3サイト構成でローテーション判断が重要。",["Aサイト","Bサイト","Cサイト","Aロング","Bメイン","Cロング","ガレージ","地下"],["ジェット","レイズ","ネオン","オーメン","アストラ","ヴァイパー","ソーヴァ","ゲッコー","スカイ","サイファー","キルジョイ","セージ"]],
["split","スプリット","assets/split.png","高低差とロープを活用するマップ。",["Aサイト","Bサイト","ミッド","ベント","メール","ヘブン","Aメイン","Bメイン"],["レイズ","ジェット","ネオン","オーメン","ヴァイパー","アストラ","ブリーチ","ゲッコー","フェイド","サイファー","キルジョイ","セージ"]],
["ascent","アセント","assets/ascent.png","中央エリアの制圧が重要なマップ。",["Aサイト","Bサイト","中央トップ","ミッド","マーケット","ツリー","Aメイン","Bメイン"],["ジェット","レイズ","フェニックス","オーメン","ブリムストーン","アストラ","ソーヴァ","フェイド","スカイ","キルジョイ","サイファー","セージ"]],
["icebox","アイスボックス","assets/icebox.png","高低差とジップラインを活用する極寒の施設。",["Aサイト","Bサイト","Aメイン","Bメイン","ミッド","キッチン","チューブ","イエロー"],["ジェット","レイズ","ネオン","ヴァイパー","ハーバー","オーメン","ソーヴァ","ケイ／オー","ゲッコー","キルジョイ","セージ","サイファー"]],
["breeze","ブリーズ","assets/breeze.png","広い空間と長距離戦が特徴。",["Aサイト","Bサイト","Aメイン","Bメイン","ミッド","ホール","ケイブ","ネスト"],["ジェット","ネオン","レイズ","ヴァイパー","ハーバー","オーメン","ソーヴァ","ケイ／オー","フェイド","サイファー","キルジョイ","チェンバー"]],
["fracture","フラクチャー","assets/fracture.png","両側から挟み込める独特の構造。",["Aサイト","Bサイト","Aメイン","Bメイン","ディッシュ","アーケード","ロープ","カンティーン"],["レイズ","ネオン","ジェット","ブリムストーン","ヴァイパー","オーメン","ブリーチ","フェイド","ゲッコー","キルジョイ","サイファー","チェンバー"]],
["pearl","パール","assets/pearl.png","ミッド支配と長い射線が特徴。",["Aサイト","Bサイト","Aメイン","Bメイン","ミッド","アート","フラワーズ","Bリンク"],["ジェット","レイズ","ネオン","オーメン","ヴァイパー","アストラ","フェイド","ソーヴァ","ゲッコー","サイファー","キルジョイ","チェンバー"]],
["lotus","ロータス","assets/lotus.png","3サイトと回転扉による素早い展開。",["Aサイト","Bサイト","Cサイト","Aメイン","Bメイン","Cメイン","ツリー","ウォーターフォール"],["レイズ","ジェット","ネオン","オーメン","ヴァイパー","アストラ","フェイド","ゲッコー","ソーヴァ","キルジョイ","サイファー","チェンバー"]],
["sunset","サンセット","assets/sunset.jpg","中央の取り合いとサイト展開が重要。",["Aサイト","Bサイト","Aメイン","Bメイン","ミッド","マーケット","ボバ","コートヤード"],["レイズ","ジェット","ネオン","オーメン","ヴァイパー","ブリムストーン","ソーヴァ","ゲッコー","フェイド","サイファー","キルジョイ","チェンバー"]],
["abyss","アビス","assets/abyss.png","落下ポイントと高低差を持つマップ。",["Aサイト","Bサイト","Aメイン","Bメイン","ミッド","ブリッジ","カンティーン","ピット"],["レイズ","ジェット","ネオン","オーメン","ヴァイパー","ハーバー","ソーヴァ","ゲッコー","フェイド","サイファー","キルジョイ","チェンバー"]],
["corrode","カロード","assets/corrode.png","城下町と採掘施設が融合した多層構造。",["Aサイト","Bサイト","ミッド","メイン","コートヤード","タワー","マーケット","トンネル"],["レイズ","ジェット","ネオン","オーメン","ヴァイパー","アストラ","ソーヴァ","フェイド","ゲッコー","サイファー","キルジョイ","チェンバー"]],
["summit","サミット","assets/summit.png","可動式の壁を備えた高低差のあるマップ。",["Aサイト","Bサイト","ミッド","マーケット","コートヤード","トンネル","トレーニングホール","メイン"],["ジェット","レイズ","ネオン","オーメン","ヴァイパー","アストラ","ソーヴァ","ゲッコー","フェイド","キルジョイ","サイファー","チェンバー"]]
];
const V=document.getElementById("view"),N=document.getElementById("nav");
N.innerHTML=maps.map(m=>`<a href="#map/${m[0]}">◈　${m[1]}</a>`).join("");
const card=m=>`<a class="card" href="#map/${m[0]}"><div class="pic"><img src="${m[2]}" alt="${m[1]}"></div><div class="info"><h3>${m[1]} <span style="float:right">›</span></h3></div></a>`;
function home(){V.innerHTML=`<div class="page"><section class="hero"><img src="${maps[0][2]}"><div class="copy"><div class="eyebrow">VALORANT MAP GUIDE</div><h1>マップを知る。<br>それが勝利への近道。</h1><p>VALORANTのマップ情報、コールアウト、役割別のおすすめエージェントを、試合中でも確認しやすい形に整理した攻略ガイド。</p></div></section><div class="head"><div><h2>マップ一覧</h2><span>全${maps.length}マップ</span></div><div class="filters"><button class="filter active">すべて</button><button class="filter">デフォルト</button><button class="filter">コンペティティブ</button><button class="filter">スイフトプレイ</button></div></div><div class="grid">${maps.map(card).join("")}</div></div>`}
function detail(id){let m=maps.find(x=>x[0]===id)||maps[0];V.innerHTML=`<div class="page"><section class="detailHero"><img src="${m[2]}"><div class="copy"><div class="eyebrow">マップ</div><h1>${m[1]}</h1><p>${m[4]}</p></div></section><div class="tabs"><button class="tab active" data-t="o">概要</button><button class="tab" data-t="l">ロケーション</button><button class="tab" data-t="a">おすすめエージェント</button><button class="tab" data-t="p">攻略のコツ</button></div><div id="body"></div></div>`;render("o",m);document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.t,m)})}
function render(t,m){let b=document.getElementById("body");if(t==="o")b.innerHTML=`<div class="cols"><section class="panel"><h2>マップ概要</h2><div class="locs">${m[5].map((x,i)=>`<div class="loc"><b>${x}</b><small>${i<2?"サイト":"重要エリア"}</small></div>`).join("")}</div></section><section class="panel"><h2>このマップのポイント</h2><div class="note">まず重要エリアの情報を取り、味方と一緒に人数差を作る。無理なピークより、次の判断をしやすい位置を確保しよう。</div></section></div>`;if(t==="l")b.innerHTML=`<div class="location-layout"><section class="panel"><h2>ロケーション / コールアウト</h2>${m[0]==="bind"?`<img class="callout-map" src="assets/bind-callouts.jpg" alt="バインドのマップ内名称">`:``}<div class="locs">${m[5].map((x,i)=>`<div class="loc"><b>${String(i+1).padStart(2,"0")}　${x}</b><small>主要コールアウト</small></div>`).join("")}</div></section>${m[0]==="bind"?`<section class="panel"><h2>バインドの基本</h2><div class="note">ミッドがなく、2つのテレポーターで離れたエリアを一気に移動できるのが特徴。A側はAショートとシャワー、B側はBロングとフッカー周辺の主導権が重要。</div><div class="source-note">基本情報：指定された攻略サイトをもとに整理</div></section>`:``}</div>`;if(t==="a")b.innerHTML=`<div class="cols"><section class="panel"><h2>おすすめエージェント</h2><div class="agents">${m[6].map(x=>`<span class="agent">${x}</span>`).join("")}</div></section><section class="panel"><h2>役割</h2><div class="note">この一覧は候補を素早く確認するためのもの。実際の採用はチーム構成とプレイスタイルに合わせて判断。</div></section></div>`;if(t==="p")b.innerHTML=`<div class="cols"><section class="panel"><h2>攻略のコツ</h2><h3>攻撃</h3><div class="note">重要エリアの情報を取って相手の配置を確認し、人数を寄せてからエントリー。</div><h3>防衛</h3><div class="note">序盤は無理に前へ出ず、情報共有を優先。敵の人数とユーティリティを見てローテーション。</div></section><section class="panel"><h2>覚えること</h2><div class="agents"><span class="agent">情報</span><span class="agent">人数</span><span class="agent">退路</span><span class="agent">ローテーション</span></div></section></div>`}
function route(){let h=location.hash.slice(1)||"home";h==="home"?home():h.startsWith("map/")?detail(h.split("/")[1]):home();window.scrollTo(0,0)}route();addEventListener("hashchange",route);
const side=document.getElementById("side"),ov=document.getElementById("overlay");document.getElementById("open").onclick=()=>{side.classList.add("open");ov.classList.add("open")};document.getElementById("close").onclick=()=>{side.classList.remove("open");ov.classList.remove("open")};ov.onclick=()=>{side.classList.remove("open");ov.classList.remove("open")};
const si=document.getElementById("search"),rs=document.getElementById("results");si.oninput=()=>{let q=si.value.trim().toLowerCase();if(!q){rs.style.display="none";return}let h=maps.filter(m=>(m[1]+m[4]+m[5].join("")+m[6].join("")).toLowerCase().includes(q));rs.innerHTML=h.map(m=>`<a class="result" href="#map/${m[0]}"><b>${m[1]}</b>　${m[4]}</a>`).join("")||'<div class="result">見つかりませんでした</div>';rs.style.display="block"};