const maps=[
{id:'bind',name:'バインド',img:'assets/bind.png',calloutImg:'assets/bind-callouts.jpg',summary:'ミッドを持たず、2つのテレポーターで攻撃ルートとローテーションを大きく変えられる2サイトマップ。',locations:['CTベース','ヘブン','ランプ','Aサイト','シャワー','Aショート','ヤシ','シャワーTP','Tベース','マーケット','噴水','Bショート','Bロング','フッカー','Bサイト','エルボー'],features:[['ミッドが存在しない','中央のミッドを取り合う代わりに、A側・B側の外周ルートと中間エリアの主導権を組み立てて攻める。'],['テレポーターが戦術の軸','A側とB側を短時間でつなげるため、音や人数を利用したフェイク、ローテーション、リテイクの判断が重要。'],['広いエリア確保が強い','一点突破だけで終わらせず、Aならシャワー・Aショート、Bならフッカー・Bロングなど複数の前線を押さえると相手の選択肢を減らせる。'],['フッカーがB側の要所','Bサイトへの進入だけでなく、ローテーションや待機位置として機能する。取れれば防衛側に対応を迫りやすい。'],['シャワーはA側の重要エリア','Aショートと組み合わせてAサイトへの圧力を作れる。防衛側に取られたままだとA攻めの自由度が下がる。'],['合わせが重要','単独で広いエリアを維持するより、フラッシュ・モク・索敵などを合わせて人数差を作る方が安定しやすい。']],recommend:['レイズ','ネオン','ウェイレイ','ブリムストーン','ヴァイパー','オーメン','スカイ','ゲッコー','KAY/O','サイファー','チェンバー','アストラ']},
{id:'haven',name:'ヘイヴン',img:'assets/haven.png',summary:'A・B・Cの3サイトを持つため、防衛側のローテーションと攻撃側の人数配分が重要。',locations:['Aサイト','Bサイト','Cサイト','Aロング','Aショート','ガレージ','Cロング','Cショート'],features:[['3サイト構成','攻撃側は守備を散らす力があり、防衛側は早い情報共有とローテーション判断が重要。'],['Bサイトが中央の要所','A・Cの両方へつながるため、中央の情報と人数がラウンド全体の判断材料になる。'],['ロングの長い射線','AロングやCロングでは遠距離の撃ち合いが発生しやすく、スモークやフラッシュで距離を詰める判断が重要。']],recommend:['ジェット','レイズ','ネオン','オーメン','アストラ','ヴァイパー','ソーヴァ','ゲッコー','スカイ','サイファー','キルジョイ','セージ']},
{id:'split',name:'スプリット',img:'assets/split.png',summary:'中央の高低差とロープを使った上下移動が特徴。狭い入口でのユーティリティー合わせが強い。',locations:['Aサイト','Bサイト','ミッド','ベント','メール','ヘブン','Aメイン','Bメイン'],features:[['ミッドが重要','中央を取るとA・B双方への圧力を作りやすく、防衛側の視線と人数を動かせる。'],['ロープで上下を切り替える','音を出す移動になるため、使うタイミングと味方のカバーを合わせたい。'],['狭い入口','チョークポイントにアビリティーを重ねると進行を止めやすく、逆に攻撃側は複数人で一気に突破する価値が高い。']],recommend:['レイズ','ジェット','ネオン','オーメン','ヴァイパー','アストラ','ブリーチ','ゲッコー','フェイド','サイファー','キルジョイ','セージ']},
{id:'ascent',name:'アセント',img:'assets/ascent.png',summary:'中央エリアと開閉式のドアがラウンドの主導権を左右する、標準的で読み合いの深い2サイトマップ。',locations:['Aサイト','Bサイト','ミッド','マーケット','ツリー','Aメイン','Bメイン','ガーデン'],features:[['中央支配が強い','ミッドを取るとマーケットやツリーへの展開が生まれ、サイトを絞らせやすい。'],['ドアを利用したサイト防衛','開閉できるドアは進入・リテイクのテンポを変える。壊すか残すかも防衛側の判断材料。'],['長い射線と角待ち','メインやサイト入口ではプリエイムと索敵が重要。人数を揃えて角を一つずつ処理すると安定する。']],recommend:['ジェット','レイズ','フェニックス','オーメン','ブリムストーン','アストラ','ソーヴァ','フェイド','スカイ','キルジョイ','サイファー','セージ']},
{id:'icebox',name:'アイスボックス',img:'assets/icebox.png',summary:'高低差、ジップライン、コンテナによる複雑な射線が特徴。サイト内の上下を理解すると戦いやすい。',locations:['Aサイト','Bサイト','Aメイン','Bメイン','ミッド','キッチン','チューブ','イエロー'],features:[['高低差が大きい','通常の水平な撃ち合いだけでなく、上から下・下から上の射線を意識する必要がある。'],['Aサイトの複数レベル','設置位置によって守り方が変わるため、設置後にどこから守るかまで決めておくと強い。'],['B側はイエローが要所','サイトへの進入と設置後の守備位置に影響するため、取り合いの価値が高い。']],recommend:['ジェット','レイズ','ネオン','ヴァイパー','ハーバー','オーメン','ソーヴァ','KAY/O','ゲッコー','キルジョイ','セージ','サイファー']},
{id:'breeze',name:'ブリーズ',img:'assets/breeze.png',summary:'広いサイトと長距離の射線を持つマップ。オープンスペースでの索敵とスモーク管理が重要。',locations:['Aサイト','Bサイト','Aメイン','Bメイン','ミッド','ホール','ケイブ','ネスト'],features:[['長距離戦が多い','遠距離武器だけでなく、フラッシュやスモークで距離を崩すことが重要。'],['中央の情報','ミッドを取ることで両サイトへの圧力が生まれ、攻撃側の選択肢が増える。'],['広いサイト','設置後に全員で同じ方向を見続けるのではなく、複数の射線を作ることが大切。']],recommend:['ジェット','ネオン','レイズ','ヴァイパー','ハーバー','オーメン','ソーヴァ','KAY/O','フェイド','サイファー','キルジョイ','チェンバー']},
{id:'fracture',name:'フラクチャー',img:'assets/fracture.png',summary:'マップ両側に攻撃ルートがあり、ロープや地下通路を使って挟み込める独特な構造。',locations:['Aサイト','Bサイト','Aメイン','Bメイン','ディッシュ','アーケード','ロープ','カンティーン'],features:[['両側から圧力を作れる','攻撃側は同じサイトに複数方向から入れるため、防衛側の配置を動かしやすい。'],['ロープ移動','上下移動を利用した不意打ちができる一方、音や移動時間を考えて使う必要がある。'],['情報の価値が高い','防衛側はどちらのサイドから来るかを早く把握し、人数を寄せすぎないことが重要。']],recommend:['レイズ','ネオン','ジェット','ブリムストーン','ヴァイパー','オーメン','ブリーチ','フェイド','ゲッコー','キルジョイ','サイファー','チェンバー']},
{id:'pearl',name:'パール',img:'assets/pearl.png',summary:'ミッドが大きく、A・B両方へ展開できる水中都市マップ。中央の取り合いがサイト選択を左右する。',locations:['Aサイト','Bサイト','Aメイン','Bメイン','ミッド','アート','フラワーズ','Bリンク'],features:[['ミッドの価値が高い','中央を確保すると複数のリンクへ展開でき、サイトを固定させない攻めができる。'],['A側は複数の進入角','メインだけに頼らず、中央側からの圧力と組み合わせることで防衛を分散できる。'],['B側は長い交戦','Bメイン周辺では遠距離の撃ち合いが起きやすく、ユーティリティーで射線を切る判断が重要。']],recommend:['ジェット','レイズ','ネオン','オーメン','ヴァイパー','アストラ','フェイド','ソーヴァ','ゲッコー','サイファー','キルジョイ','チェンバー']},
{id:'lotus',name:'ロータス',img:'assets/lotus.png',summary:'3サイトと回転扉・破壊可能な扉によって、攻守ともにローテーションと情報戦が複雑になる。',locations:['Aサイト','Bサイト','Cサイト','Aメイン','Bメイン','Cメイン','ツリー','ウォーターフォール'],features:[['3サイト構成','攻撃側は防衛の人数を散らしやすく、防衛側は情報を取ってから寄せる判断が重要。'],['回転扉','一度使うと位置が変わるため、音とタイミングを利用してフェイクやローテーションを作れる。'],['破壊可能な扉','閉じている状態を維持するか開けるかでサイトの射線が変わる。']],recommend:['レイズ','ジェット','ネオン','オーメン','ヴァイパー','アストラ','フェイド','ゲッコー','ソーヴァ','キルジョイ','サイファー','チェンバー']},
{id:'sunset',name:'サンセット',img:'assets/sunset.jpg',summary:'中央の取り合いとサイトへの複数ルートを組み合わせる、読み合い重視の2サイトマップ。',locations:['Aサイト','Bサイト','Aメイン','Bメイン','ミッド','マーケット','ボバ','コートヤード'],features:[['中央の主導権','ミッドを確保するとマーケットなどを経由してサイトへの選択肢が増える。'],['狭い入口を合わせる','サイト入口にスモークやフラッシュを重ね、味方のエントリーを通すことが重要。'],['防衛の情報共有','中央とメインを同時に見られないため、早い報告と無理をしないリテイク判断が求められる。']],recommend:['レイズ','ジェット','ネオン','オーメン','ヴァイパー','ブリムストーン','ソーヴァ','ゲッコー','フェイド','サイファー','キルジョイ','チェンバー']},
{id:'abyss',name:'アビス',img:'assets/abyss.png',summary:'マップ外へ落下する危険があり、端の足場や高低差を利用した大胆な進入が可能。',locations:['Aサイト','Bサイト','Aメイン','Bメイン','ミッド','ブリッジ','カンティーン','ピット'],features:[['落下の危険','マップ端では通常の壁際とは違うリスクがあり、追い込みやノックバック系のプレイも警戒したい。'],['広い通路と高低差','射線が長くなる場所と狭い場所が混在するため、武器とアビリティーの使い分けが重要。'],['設置後の立ち位置','落下を避けるだけでなく、解除への射線をどこから作るかを先に決めると守りやすい。']],recommend:['レイズ','ジェット','ネオン','オーメン','ヴァイパー','ハーバー','ソーヴァ','ゲッコー','フェイド','サイファー','キルジョイ','チェンバー']},
{id:'corrode',name:'カロード',img:'assets/corrode.png',summary:'広い中央エリアと複数の高低差を持ち、前線の取り合いからサイトへの展開を作る新しい2サイトマップ。',locations:['Aサイト','Bサイト','ミッド','メイン','コートヤード','タワー','マーケット','トンネル'],features:[['中央のスペースが重要','サイトだけを見るより、中央の前線をどこまで取れるかで攻撃の選択肢が変わる。'],['高低差を意識','上下の射線があるため、ピークする高さとカバー位置を合わせる必要がある。'],['ローテーション管理','広いエリアを取られたまま放置すると防衛の寄りが遅れるため、情報を取って早めに判断する。']],recommend:['レイズ','ジェット','ネオン','オーメン','ヴァイパー','アストラ','ソーヴァ','フェイド','ゲッコー','サイファー','キルジョイ','チェンバー']},
{id:'summit',name:'サミット',img:'assets/summit.png',summary:'高低差と可動式の構造を持つマップ。中央の主導権とサイト進入前の情報戦が重要。',locations:['Aサイト','Bサイト','ミッド','マーケット','コートヤード','トンネル','トレーニングホール','メイン'],features:[['中央をどう使うか','中央から両サイトへ展開できるため、早い段階で相手の配置を確認する価値が高い。'],['可動式の構造','ラウンド中に通路や射線が変化するため、固定されたセオリーだけでなく、その時点の状況を見る。'],['前線の維持','サイトへ入る前に無理なピークを繰り返さず、アビリティーを残してエントリーを作る。']],recommend:['ジェット','レイズ','ネオン','オーメン','ヴァイパー','アストラ','ソーヴァ','ゲッコー','フェイド','キルジョイ','サイファー','チェンバー']}
];
const agentRoles={デュエリスト:['ジェット','レイズ','ネオン','フェニックス','レイナ','ヨル','アイソ','ウェイレイ'],センチネル:['キルジョイ','サイファー','セージ','チェンバー','デッドロック','ヴァイス','ヴィトー'],イニシエーター:['ソーヴァ','スカイ','フェイド','ゲッコー','ブリーチ','KAY/O','テホ'],コントローラー:['オーメン','ブリムストーン','ヴァイパー','アストラ','ハーバー','クローヴ','ミクス']};
const localAgents={
'KAY/O':'assets/agents/kayo.png','ヨル':'assets/agents/yoru.jpg','レイナ':'assets/agents/reyna.jpg','オーメン':'assets/agents/omen.jpg','ヴァイパー':'assets/agents/viper.jpg','ブリムストーン':'assets/agents/brimstone.jpg','ネオン':'assets/agents/neon.jpg','キルジョイ':'assets/agents/killjoy.jpg','レイズ':'assets/agents/raze.jpg','ゲッコー':'assets/agents/gekko.jpg','サイファー':'assets/agents/cypher.jpg','ジェット':'assets/agents/jett.jpg'};
const allAgents=[...new Set(Object.values(agentRoles).flat())];
const V=document.getElementById('view'),N=document.getElementById('nav');N.innerHTML=maps.map(m=>`<a href="#map/${m.id}">◈　${m.name}</a>`).join('');
let apiAgents=[];
async function loadAgentApi(){try{const r=await fetch('https://valorant-api.com/v1/agents?language=ja-JP&isPlayableCharacter=true');const j=await r.json();apiAgents=j.data||[];}catch(e){apiAgents=[]}}
function agentImage(name){if(localAgents[name])return localAgents[name];const a=apiAgents.find(x=>x.displayName===name || (name==='KAY/O'&&x.displayName==='KAY/O'));return a?.fullPortrait||a?.displayIcon||''}
function home(){V.innerHTML=`<div class="page"><section class="hero"><img src="${maps[0].img}"><div class="copy"><div class="eyebrow">VALORANT MAP GUIDE / RANKED</div><h1>マップを知る。<br>それが勝利への近道。</h1><p>ランク戦を前提に、マップの全体像・コールアウト・マップ特有の考え方・おすすめエージェントを、試合中にも確認しやすい形で整理した攻略ガイド。</p></div></section><div class="head"><div><h2>マップ一覧</h2><span>全${maps.length}マップ / ランク想定</span></div></div><div class="grid">${maps.map(m=>`<a class="card" href="#map/${m.id}"><div class="pic"><img src="${m.img}" alt="${m.name}"></div><div class="info"><h3>${m.name} <span style="float:right">›</span></h3></div></a>`).join('')}</div></div>`}
function detail(id){const m=maps.find(x=>x.id===id)||maps[0];V.innerHTML=`<div class="page"><section class="detailHero"><img src="${m.img}" alt="${m.name}"><div class="copy"><div class="eyebrow">${m.name}</div><h1>マップ</h1><p>${m.summary}</p></div></section><div class="tabs"><button class="tab active" data-t="map">マップ</button><button class="tab" data-t="feature">特徴</button><button class="tab" data-t="agent">おすすめエージェント</button><button class="tab" data-t="tips">攻略のコツ</button></div><div id="body"></div></div>`;render('map',m);document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.t,m)})}
function render(t,m){const b=document.getElementById('body');if(t==='map')b.innerHTML=`<div class="cols"><section class="panel"><h2>マップ全体像</h2><img class="map-large" src="${m.img}" alt="${m.name} マップ"></section><section class="panel"><h2>名称一覧</h2><div class="locations">${m.locations.map((x,i)=>`<div class="loc"><b>${String(i+1).padStart(2,'0')}　${x}</b><small>コールアウト</small></div>`).join('')}</div>${m.calloutImg?`<div class="source-note">バインドの名称画像は指定された画像をそのまま使用しています。</div>`:''}</section></div>${m.calloutImg?`<section class="panel" style="margin-top:18px"><h2>名称マップ</h2><img class="callout-map" src="${m.calloutImg}" alt="${m.name} 名称マップ"></section>`:''}`;
if(t==='feature')b.innerHTML=`<section class="panel"><h2>${m.name}の特徴</h2><div class="feature-list">${m.features.map(x=>`<div class="feature"><b>${x[0]}</b><p>${x[1]}</p></div>`).join('')}</div>${m.id==='bind'?`<div class="source-note">バインドの基本情報は、GameWith・note・SepiaMars・eSportsジャーニーの情報を参照して整理しています。<br><a href="https://gamewith.jp/valorant/article/show/355145" target="_blank">GameWith</a> / <a href="https://note.com/clean_ixia6955/n/ndd6f0adf246c" target="_blank">note</a> / <a href="https://www.sepiamars.work/entry/2021/08/01/210337" target="_blank">SepiaMars</a> / <a href="https://esports-journey.jp/bind-map-valorant/" target="_blank">eSportsジャーニー</a></div>`:''}</section>`;
if(t==='agent')b.innerHTML=`<div class="role-groups">${Object.entries(agentRoles).map(([role,names])=>`<section class="role-group"><h3>${role}</h3><div class="chips">${names.filter(n=>m.recommend.includes(n)).map(n=>`<span class="chip">${n}</span>`).join('')||'<span class="chip">構成に応じて選択</span>'}</div></section>`).join('')}</div><section class="panel" style="margin-top:18px"><h2>おすすめ候補</h2><div class="agents">${m.recommend.map(n=>`<div class="agent-card"><div class="agent-art"><img src="${agentImage(n)}" alt="${n}" loading="lazy"></div><div class="agent-info"><div class="agent-name">${n}</div><div class="role">${roleOf(n)}</div></div></div>`).join('')}</div><div class="source-note">キャラクター画像は、提供された画像を優先して元画像のまま使用。未提供エージェントはVALORANT公式エージェント一覧に対応する公式素材を表示します。</div></section>`;
if(t==='tips')b.innerHTML=`<div class="cols"><section class="panel"><h2>攻撃</h2><div class="note">ラウンド開始時に「どのエリアを取るか」を決め、味方のアビリティーを合わせて前線を広げる。サイトに入る前に情報を取り、無理なピークで人数差を作られないことを意識する。</div><h3>設置後</h3><div class="note">全員がサイト内に残るのではなく、解除音に合わせて複数の射線を作れる位置へ分散する。残っているアビリティーと人数を見て、無理なキル取りより時間を使わせる。</div></section><section class="panel"><h2>防衛</h2><div class="note">序盤の接敵だけでラウンド全体を決めず、情報を取ってからローテーションする。前線を失った場合は取り返す価値と残り時間を比較して判断する。</div><h3>リテイク</h3><div class="note">残っているユーティリティーを合わせ、同時に複数方向から入る。単独でサイトへ飛び込むより、味方との距離を保ってトレードを作る。</div></section></div>`}
function roleOf(n){for(const [r,a] of Object.entries(agentRoles))if(a.includes(n))return r;return 'エージェント'}
function agentsPage(){V.innerHTML=`<div class="page"><div class="head"><div><h2>全エージェント</h2><span>ランクで使える候補を日本語で一覧</span></div></div><section class="panel"><div class="agents">${allAgents.map(n=>`<div class="agent-card"><div class="agent-art"><img src="${agentImage(n)}" alt="${n}" loading="lazy"></div><div class="agent-info"><div class="agent-name">${n}</div><div class="role">${roleOf(n)}</div></div></div>`).join('')}</div></section><div class="source-note" style="margin-top:14px">公式エージェント一覧：<a href="https://playvalorant.com/ja-jp/agents/" target="_blank">VALORANT公式</a></div></div>`}
function route(){const h=location.hash.slice(1)||'home';if(h==='home')home();else if(h==='agents')agentsPage();else if(h.startsWith('map/'))detail(h.split('/')[1]);else home();window.scrollTo(0,0)}
route();addEventListener('hashchange',route);loadAgentApi().then(()=>{if(location.hash==='#agents'||location.hash.startsWith('#map/'))route()});
const side=document.getElementById('side'),ov=document.getElementById('overlay');document.getElementById('open').onclick=()=>{side.classList.add('open');ov.classList.add('open')};document.getElementById('close').onclick=()=>{side.classList.remove('open');ov.classList.remove('open')};ov.onclick=()=>{side.classList.remove('open');ov.classList.remove('open')};
const si=document.getElementById('search'),rs=document.getElementById('results');si.oninput=()=>{const q=si.value.trim().toLowerCase();if(!q){rs.style.display='none';return}const out=[];maps.forEach(m=>{if((m.name+m.summary+m.locations.join('')+m.features.flat().join('')).toLowerCase().includes(q))out.push(`<a class="result" href="#map/${m.id}"><b>${m.name}</b>　マップ情報</a>`)});allAgents.forEach(n=>{if(n.toLowerCase().includes(q))out.push(`<a class="result" href="#agents"><b>${n}</b>　エージェント</a>`)});rs.innerHTML=`<div class="results-box">${out.join('')||'<div class="result">見つかりませんでした</div>'}</div>`;rs.style.display='block'};
document.addEventListener('click',e=>{if(!e.target.closest('.search')&&!e.target.closest('#results'))rs.style.display='none'});
